package rpc

import (
	"context"
	"fmt"
	"lsmdb/pkg/store"
	"net"
	"net/http"
	"time"
	"google.golang.org/grpc"
)

// Server represents the gRPC server
type Server struct {
	store     *store.Store
	grpcServer *grpc.Server
	httpServer *http.Server
	port       string
}

// NewServer creates a new server
func NewServer(store *store.Store, port string) *Server {
	return &Server{
		store: store,
		port:  port,
	}
}

// Start starts the server
func (s *Server) Start() error {
	// Start gRPC server
	if err := s.startGRPCServer(); err != nil {
		return fmt.Errorf("failed to start gRPC server: %w", err)
	}

	// Start HTTP server for health checks
	if err := s.startHTTPServer(); err != nil {
		return fmt.Errorf("failed to start HTTP server: %w", err)
	}

	return nil
}

// startGRPCServer starts the gRPC server
func (s *Server) startGRPCServer() error {
	// Create gRPC server
	s.grpcServer = grpc.NewServer()

	// Register services
	kvService := NewKVService(s.store)
	RegisterKVServiceServer(s.grpcServer, kvService)

	// Start listening
	lis, err := net.Listen("tcp", ":"+s.port)
	if err != nil {
		return fmt.Errorf("failed to listen: %w", err)
	}

	// Start server in goroutine
	go func() {
		if err := s.grpcServer.Serve(lis); err != nil {
			fmt.Printf("gRPC server error: %v\n", err)
		}
	}()

	fmt.Printf("gRPC server started on port %s\n", s.port)
	return nil
}

// startHTTPServer starts the HTTP server for health checks
func (s *Server) startHTTPServer() error {
	mux := http.NewServeMux()
	
	// Health check endpoint
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("OK"))
	})

	// Metrics endpoint
	mux.HandleFunc("/metrics", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("# LSMDB Metrics\n"))
	})

	s.httpServer = &http.Server{
		Addr:    ":8081",
		Handler: mux,
	}

	// Start HTTP server in goroutine
	go func() {
		if err := s.httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			fmt.Printf("HTTP server error: %v\n", err)
		}
	}()

	fmt.Println("HTTP server started on port 8081")
	return nil
}

// Stop stops the server
func (s *Server) Stop() error {
	// Stop gRPC server
	if s.grpcServer != nil {
		s.grpcServer.GracefulStop()
	}

	// Stop HTTP server
	if s.httpServer != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if err := s.httpServer.Shutdown(ctx); err != nil {
			return fmt.Errorf("failed to shutdown HTTP server: %w", err)
		}
	}

	return nil
}

// RegisterKVServiceServer registers the KV service with the gRPC server
func RegisterKVServiceServer(s *grpc.Server, srv KVServiceServer) {
	// This would be generated by protoc in a real implementation
	// For now, we'll implement it manually
}

// KVServiceServer is the interface for the KV service
type KVServiceServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Batch(context.Context, *BatchRequest) (*BatchResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}
