// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: pkg/proto/data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocialPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Fullname      string                 `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Replies       int32                  `protobuf:"varint,6,opt,name=replies,proto3" json:"replies,omitempty"`
	Likes         int32                  `protobuf:"varint,7,opt,name=likes,proto3" json:"likes,omitempty"`
	Retweets      int32                  `protobuf:"varint,8,opt,name=retweets,proto3" json:"retweets,omitempty"`
	Text          string                 `protobuf:"bytes,9,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialPost) Reset() {
	*x = SocialPost{}
	mi := &file_pkg_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialPost) ProtoMessage() {}

func (x *SocialPost) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialPost.ProtoReflect.Descriptor instead.
func (*SocialPost) Descriptor() ([]byte, []int) {
	return file_pkg_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *SocialPost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SocialPost) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SocialPost) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *SocialPost) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SocialPost) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SocialPost) GetReplies() int32 {
	if x != nil {
		return x.Replies
	}
	return 0
}

func (x *SocialPost) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *SocialPost) GetRetweets() int32 {
	if x != nil {
		return x.Retweets
	}
	return 0
}

func (x *SocialPost) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_pkg_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_pkg_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *KeyValue) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_pkg_proto_data_proto protoreflect.FileDescriptor

const file_pkg_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/data.proto\x12\x0flsmdb.pkg.proto\"\xe1\x01\n" +
	"\n" +
	"SocialPost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfullname\x18\x03 \x01(\tR\bfullname\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\areplies\x18\x06 \x01(\x05R\areplies\x12\x14\n" +
	"\x05likes\x18\a \x01(\x05R\x05likes\x12\x1a\n" +
	"\bretweets\x18\b \x01(\x05R\bretweets\x12\x12\n" +
	"\x04text\x18\t \x01(\tR\x04text\"j\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeletedB\rZ\v./pkg/protob\x06proto3"

var (
	file_pkg_proto_data_proto_rawDescOnce sync.Once
	file_pkg_proto_data_proto_rawDescData []byte
)

func file_pkg_proto_data_proto_rawDescGZIP() []byte {
	file_pkg_proto_data_proto_rawDescOnce.Do(func() {
		file_pkg_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_data_proto_rawDesc), len(file_pkg_proto_data_proto_rawDesc)))
	})
	return file_pkg_proto_data_proto_rawDescData
}

var file_pkg_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_data_proto_goTypes = []any{
	(*SocialPost)(nil), // 0: lsmdb.pkg.proto.SocialPost
	(*KeyValue)(nil),   // 1: lsmdb.pkg.proto.KeyValue
}
var file_pkg_proto_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_data_proto_init() }
func file_pkg_proto_data_proto_init() {
	if File_pkg_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_data_proto_rawDesc), len(file_pkg_proto_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_data_proto_goTypes,
		DependencyIndexes: file_pkg_proto_data_proto_depIdxs,
		MessageInfos:      file_pkg_proto_data_proto_msgTypes,
	}.Build()
	File_pkg_proto_data_proto = out.File
	file_pkg_proto_data_proto_goTypes = nil
	file_pkg_proto_data_proto_depIdxs = nil
}
